import Image from "next/image";
import Link from "next/link";
import { ArrowLeft, ArrowUpRight, ExternalLink } from "lucide-react";
import { type PortfolioCase, maturityLabel } from "@/data/cases";
import { PortfolioLayout } from "@/components/portfolio/PortfolioLayout";

export function CasePage({ item }: { item: PortfolioCase }) {
  return <PortfolioLayout><article>
    <header className="bg-[#07111f] px-6 py-16 text-white lg:px-10 lg:py-24"><div className="mx-auto max-w-5xl"><Link href="/casos" className="inline-flex items-center gap-2 text-sm text-white/65 transition hover:text-white"><ArrowLeft size={16} /> Todos os casos</Link><p className="mt-12 font-mono text-xs uppercase tracking-[0.2em] text-[#79aef4]">{item.productName} · {maturityLabel[item.maturity]}</p><h1 className="mt-5 max-w-4xl font-[family-name:var(--font-display)] text-4xl font-medium leading-[1.02] tracking-[-0.055em] sm:text-6xl">{item.title}</h1><p className="mt-8 max-w-3xl text-lg leading-8 text-white/72">{item.summary.context} {item.summary.conflict}</p><div className="mt-10 grid max-w-4xl gap-3 sm:grid-cols-3"><Fact title="Contexto" text={item.summary.context} /><Fact title="Conflito" text={item.summary.conflict} /><Fact title="Evidência" text={item.summary.evidence} /></div></div></header>

    <div className="px-6 py-16 lg:px-10 lg:py-24"><div className="mx-auto grid max-w-5xl gap-16">
      <section className="grid gap-8 lg:grid-cols-[.8fr_1.2fr]"><p className="font-mono text-xs uppercase tracking-[0.2em] text-[#2166c9]">A decisão</p><div><h2 className="font-[family-name:var(--font-display)] text-3xl font-semibold tracking-[-0.045em] sm:text-4xl">O que precisava acontecer</h2><p className="mt-5 text-lg leading-8 text-slate-600">{item.objective}</p><p className="mt-8 rounded-2xl border border-[#07111f]/10 bg-white p-6 text-base leading-7 text-slate-700"><strong className="block font-[family-name:var(--font-display)] text-lg text-[#07111f]">Decisão tomada</strong><span className="mt-2 block">{item.decision}</span></p></div></section>

      {item.media.map((media) => <figure key={media.src} className="overflow-hidden rounded-[1.75rem] bg-[#07111f]">{media.type === "video" ? <video src={media.src} controls playsInline preload="metadata" className="aspect-video w-full" aria-label={media.alt} /> : <Image src={media.src} alt={media.alt} width={1400} height={788} className="aspect-video w-full object-cover" />}{media.caption ? <figcaption className="px-5 py-4 text-sm text-white/65">{media.caption}</figcaption> : null}</figure>)}

      <section className="grid gap-8 lg:grid-cols-[.8fr_1.2fr]"><p className="font-mono text-xs uppercase tracking-[0.2em] text-[#2166c9]">Pessoas e limites</p><div className="grid gap-5 sm:grid-cols-2"><div className="rounded-2xl border border-[#07111f]/10 bg-white p-6"><h2 className="font-[family-name:var(--font-display)] text-xl font-semibold">Quem estava no contexto</h2><ul className="mt-5 space-y-4">{item.actors.map((actor) => <li key={actor.name}><strong className="block text-sm">{actor.name}</strong><span className="text-sm leading-6 text-slate-600">{actor.need}</span></li>)}</ul></div><div className="rounded-2xl bg-[#eaf1fb] p-6"><h2 className="font-[family-name:var(--font-display)] text-xl font-semibold">Restrições reais</h2><ul className="mt-5 space-y-3 text-sm leading-6 text-slate-700">{item.constraints.map((constraint) => <li key={constraint}>— {constraint}</li>)}</ul></div></div></section>

      <section className="grid gap-8 lg:grid-cols-[.8fr_1.2fr]"><p className="font-mono text-xs uppercase tracking-[0.2em] text-[#2166c9]">Trade-off</p><div>{item.options.length ? <div className="mb-5 grid gap-3">{item.options.map((option) => <div key={option.name} className="rounded-2xl border border-[#07111f]/10 bg-white p-5"><h3 className="font-semibold">{option.name}</h3><p className="mt-2 text-sm text-slate-600">Atrativo: {option.appeal}</p><p className="mt-1 text-sm text-slate-600">Custo: {option.cost}</p></div>)}</div> : <p className="mb-5 rounded-2xl border border-dashed border-[#2166c9]/35 bg-[#eaf1fb]/60 p-5 text-sm leading-6 text-slate-600">As alternativas comparadas não estão documentadas publicamente. Esta lacuna permanece visível para não transformar suposições em narrativa.</p>}<div className="grid gap-3 sm:grid-cols-2"><Trade label="O que a escolha trouxe" text={item.tradeoff.gained} /><Trade label="O que ficou de fora" text={item.tradeoff.sacrificed} /><Trade label="Risco assumido" text={item.tradeoff.risk} /><Trade label="Como foi mitigado" text={item.tradeoff.mitigation} /></div></div></section>

      <section className="grid gap-8 lg:grid-cols-[.8fr_1.2fr]"><p className="font-mono text-xs uppercase tracking-[0.2em] text-[#2166c9]">Evidência e continuidade</p><div><div className="grid gap-3 sm:grid-cols-2">{item.evidence.map((evidence) => <div key={evidence.value} className="rounded-2xl bg-[#07111f] p-5 text-white"><strong className="font-[family-name:var(--font-display)] text-2xl">{evidence.value}</strong><p className="mt-2 text-sm leading-6 text-white/65">{evidence.meaning}</p></div>)}</div><Outcome title="O que está documentado" lines={item.outcome.improved} /><Outcome title="O que ainda não se sabe" lines={item.outcome.unknown} muted /><Outcome title="O que piorou ou continuou limitado" lines={item.outcome.worsened} muted /><div className="mt-8 rounded-2xl border border-[#07111f]/10 bg-white p-6"><h2 className="font-[family-name:var(--font-display)] text-xl font-semibold">Papel de Emanuel</h2><p className="mt-3 text-sm leading-7 text-slate-600">{item.role}</p><h3 className="mt-6 font-[family-name:var(--font-display)] text-lg font-semibold">O que faria diferente hoje</h3><p className="mt-2 text-sm leading-7 text-slate-600">{item.retrospective}</p></div></div></section>

      {item.validationNeeded.length ? <aside className="rounded-[1.5rem] border border-[#d99a17]/35 bg-[#fff8e6] p-6"><p className="font-mono text-[10px] uppercase tracking-[0.18em] text-[#8a5b00]">Em validação com Emanuel</p><h2 className="mt-3 font-[family-name:var(--font-display)] text-2xl font-semibold">O que falta confirmar antes de aprofundar este case</h2><ul className="mt-5 grid gap-2 text-sm leading-6 text-slate-700 sm:grid-cols-2">{item.validationNeeded.map((need) => <li key={need}>— {need}</li>)}</ul></aside> : null}
      <div className="flex flex-wrap gap-4"><Link href="/contato" className="inline-flex items-center gap-2 rounded-full bg-[#07111f] px-5 py-3 text-sm font-semibold text-white transition hover:bg-[#2166c9]">Conte o que não está funcionando <ArrowUpRight size={16} /></Link>{item.externalLink ? <a href={item.externalLink.href} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-full border border-[#07111f]/15 px-5 py-3 text-sm font-semibold transition hover:border-[#2166c9] hover:text-[#2166c9]">{item.externalLink.label} <ExternalLink size={16} /></a> : null}</div>
    </div></div>
  </article></PortfolioLayout>;
}

function Fact({ title, text }: { title: string; text: string }) { return <div className="border-l border-white/25 pl-4"><p className="font-mono text-[10px] uppercase tracking-[0.16em] text-[#79aef4]">{title}</p><p className="mt-2 text-sm leading-6 text-white/72">{text}</p></div>; }
function Trade({ label, text }: { label: string; text: string }) { return <div className="rounded-2xl border border-[#07111f]/10 bg-white p-5"><h3 className="text-sm font-semibold">{label}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{text}</p></div>; }
function Outcome({ title, lines, muted = false }: { title: string; lines: string[]; muted?: boolean }) { if (!lines.length) return null; return <div className={`mt-5 rounded-2xl p-5 ${muted ? "bg-[#eaf1fb]" : "bg-white border border-[#07111f]/10"}`}><h3 className="text-sm font-semibold">{title}</h3><ul className="mt-3 space-y-2 text-sm leading-6 text-slate-600">{lines.map((line) => <li key={line}>— {line}</li>)}</ul></div>; }
