import Link from "next/link";
import { ArrowDownRight, ArrowUpRight } from "lucide-react";
import { portfolioCases } from "@/data/cases";
import { CaseCard } from "@/components/portfolio/CaseCard";
import { PortfolioLayout } from "@/components/portfolio/PortfolioLayout";

const problems = ["Um processo manual gerando retrabalho", "Um fluxo espalhado entre planilhas e mensagens", "Um sistema que já não acompanha a operação", "Uma boa ideia que ainda não encontrou uma forma testável"];
const help = [
  ["Processo existente", "Transformar uma operação confusa em sistema ou melhoria que as pessoas conseguem usar."],
  ["Produto fragmentado", "Reorganizar fluxos e prioridades para que a evolução volte a fazer sentido."],
  ["Ideia sem forma", "Dar forma a uma hipótese, protótipo e caminho de validação."],
];
const method = [["Entender", "Qual tensão precisa mudar — para quem e em qual rotina?"], ["Estruturar", "Que fluxo, regra e critério deixam a decisão mais clara?"], ["Construir", "Como transformar a decisão em algo utilizável?"], ["Continuar", "O que a solução precisa aprender e evoluir depois da entrega?"]];

export function ProblemPortfolioHome() {
  const [events, itesam, criative] = portfolioCases;
  return <PortfolioLayout><div>
    <section className="relative overflow-hidden bg-[#07111f] px-6 py-20 text-white lg:px-10 lg:py-32"><div aria-hidden="true" className="editorial-grid absolute inset-0 opacity-30" /><div className="relative mx-auto max-w-7xl"><p className="font-mono text-xs uppercase tracking-[0.22em] text-[#79aef4]">Emanuel Santos · desenvolvimento e produto</p><h1 className="mt-6 max-w-5xl font-[family-name:var(--font-display)] text-5xl font-medium leading-[.98] tracking-[-0.065em] sm:text-7xl">Processos confusos podem se tornar produtos claros.</h1><p className="mt-8 max-w-2xl text-lg leading-8 text-white/70">Do papel, das planilhas e dos sistemas fragmentados até ideias ainda sem forma: organizo contexto, experiência e desenvolvimento para criar soluções utilizáveis e capazes de evoluir.</p><div className="mt-10 flex flex-wrap gap-4"><Link href="/contato" className="inline-flex items-center gap-2 rounded-full bg-white px-5 py-3 text-sm font-semibold text-[#07111f] transition hover:bg-[#dbeafe]">Conte o que não está funcionando <ArrowUpRight size={16} /></Link><Link href="/casos" className="inline-flex items-center gap-2 rounded-full border border-white/25 px-5 py-3 text-sm font-semibold transition hover:border-white">Ver casos reais <ArrowDownRight size={16} /></Link></div></div></section>
    <section className="px-6 py-20 lg:px-10 lg:py-28"><div className="mx-auto max-w-7xl"><p className="font-mono text-xs uppercase tracking-[0.22em] text-[#2166c9]">Talvez o problema comece assim</p><div className="mt-8 grid gap-3 sm:grid-cols-2">{problems.map((problem, index) => <p key={problem} className="rounded-2xl border border-[#07111f]/10 bg-white p-6 font-[family-name:var(--font-display)] text-xl font-medium tracking-[-0.03em]"><span className="mr-3 font-mono text-xs text-[#2166c9]">0{index + 1}</span>{problem}</p>)}</div></div></section>
    <section className="bg-[#eaf1fb] px-6 py-20 lg:px-10 lg:py-28"><div className="mx-auto max-w-7xl"><div className="mb-10 flex flex-col justify-between gap-5 lg:flex-row lg:items-end"><div><p className="font-mono text-xs uppercase tracking-[0.22em] text-[#2166c9]">Case principal</p><h2 className="mt-4 font-[family-name:var(--font-display)] text-4xl font-medium tracking-[-0.05em] sm:text-5xl">Uma operação física organizada por um fluxo digital.</h2></div><p className="max-w-md leading-7 text-slate-600">O Events é a primeira prova: regras, pessoas e operação precisavam coexistir sem criar mais trabalho para quem estava no local.</p></div><CaseCard item={events} featured /></div></section>
    <section className="px-6 py-20 lg:px-10 lg:py-28"><div className="mx-auto max-w-7xl"><p className="font-mono text-xs uppercase tracking-[0.22em] text-[#2166c9]">Formas de ajudar</p><div className="mt-8 grid gap-4 md:grid-cols-3">{help.map(([title, text], index) => <article key={title} className="rounded-[1.5rem] border border-[#07111f]/10 bg-white p-7"><span className="font-mono text-xs text-[#2166c9]">0{index + 1}</span><h2 className="mt-12 font-[family-name:var(--font-display)] text-2xl font-semibold tracking-[-0.04em]">{title}</h2><p className="mt-4 text-sm leading-7 text-slate-600">{text}</p></article>)}</div></div></section>
    <section className="bg-[#07111f] px-6 py-20 text-white lg:px-10 lg:py-28"><div className="mx-auto max-w-7xl"><p className="font-mono text-xs uppercase tracking-[0.22em] text-[#79aef4]">Como trabalho</p><h2 className="mt-4 max-w-3xl font-[family-name:var(--font-display)] text-4xl font-medium tracking-[-0.05em] sm:text-5xl">Entender, estruturar, construir e continuar.</h2><ol className="mt-10 grid overflow-hidden rounded-[1.5rem] border border-white/15 md:grid-cols-4">{method.map(([title, question], index) => <li key={title} className="min-h-48 border-b border-white/10 p-6 last:border-b-0 md:border-b-0 md:border-r md:last:border-r-0"><span className="font-mono text-xs text-[#79aef4]">0{index + 1}</span><h3 className="mt-8 font-[family-name:var(--font-display)] text-2xl font-semibold">{title}</h3><p className="mt-3 text-sm leading-6 text-white/65">{question}</p></li>)}</ol><Link href="/como-trabalho" className="mt-8 inline-flex items-center gap-2 text-sm font-semibold text-[#b9d6ff] hover:gap-3">Ver como as decisões se conectam <ArrowUpRight size={16} /></Link></div></section>
    <section className="px-6 py-20 lg:px-10 lg:py-28"><div className="mx-auto max-w-7xl"><p className="font-mono text-xs uppercase tracking-[0.22em] text-[#2166c9]">Outras evidências</p><div className="mt-8 grid gap-5 lg:grid-cols-2"><CaseCard item={itesam} /><CaseCard item={criative} /></div><Link href="/exploracoes" className="mt-8 inline-flex items-center gap-2 text-sm font-semibold text-[#2166c9] hover:gap-3">Ver explorações com estado declarado <ArrowUpRight size={16} /></Link></div></section>
    <section className="bg-[#10243f] px-6 py-20 text-white lg:px-10 lg:py-28"><div className="mx-auto grid max-w-7xl gap-8 lg:grid-cols-[1fr_.8fr] lg:items-end"><div><p className="font-mono text-xs uppercase tracking-[0.22em] text-[#79aef4]">Sobre Emanuel</p><h2 className="mt-4 max-w-3xl font-[family-name:var(--font-display)] text-4xl font-medium tracking-[-0.05em] sm:text-5xl">Desenvolvimento é a base. Pensamento de produto é a forma de conectar as peças.</h2></div><div><p className="leading-7 text-white/70">A trajetória completa reúne formação, prática profissional e projetos autorais — sem tirar o foco do problema que a pessoa chegou para resolver.</p><Link href="/sobre" className="mt-6 inline-flex items-center gap-2 text-sm font-semibold text-[#b9d6ff] hover:gap-3">Conhecer a trajetória <ArrowUpRight size={16} /></Link></div></div></section>
    <section className="bg-[#07111f] px-6 py-20 text-white lg:px-10 lg:py-28"><div className="mx-auto max-w-7xl"><p className="font-mono text-xs uppercase tracking-[0.22em] text-[#79aef4]">Vamos começar por uma conversa</p><h2 className="mt-5 max-w-4xl font-[family-name:var(--font-display)] text-4xl font-medium tracking-[-0.05em] sm:text-6xl">Conte o que hoje não está funcionando.</h2><p className="mt-6 max-w-2xl text-lg leading-8 text-white/70">Pode ser um projeto, uma oportunidade profissional, parceria ou uma conversa de diagnóstico.</p><Link href="/contato" className="mt-9 inline-flex items-center gap-2 rounded-full bg-white px-5 py-3 text-sm font-semibold text-[#07111f] transition hover:bg-[#dbeafe]">Ir para contato <ArrowUpRight size={16} /></Link></div></section>
  </div></PortfolioLayout>;
}
