import Image from "next/image";
import Link from "next/link";
import { ArrowUpRight, Github, Layers3, Linkedin, Mail } from "lucide-react";
import { HomeHero } from "@/components/pages/HomeHero";
import { TrajectorySection } from "@/components/pages/TrajectorySection";

const projects = [
  { number: "01", title: "Rotas Inteligentes", summary: "Mobilidade urbana com mais clareza, contexto e possibilidades de escolha.", description: "Um projeto autoral criado para transformar dúvidas comuns de deslocamento em uma experiência simples de consultar, comparar e organizar trajetos.", role: "Conceito, pesquisa, experiência e protótipo por Emanuel Santos.", href: "https://www.figma.com/proto/p2nGg4cLvSvimsAAhEkviB/Rotas-Inteligentes?node-id=214-1010&starting-point-node-id=214%3A1010", image: "/images/rotas-inteligentes.png", featured: true },
  { number: "02", title: "Criative Lab", summary: "Uma casa para que projetos acadêmicos continuem visíveis depois da apresentação.", description: "Produto digital para receber, organizar, avaliar e publicar a produção acadêmica com contexto para estudantes, docentes e instituições.", role: "Estratégia de produto, identidade, experiência e desenvolvimento.", href: "#contato", image: "/images/creative-lab.png", featured: false },
  { number: "03", title: "Fince", summary: "Uma experiência financeira pessoal feita para reduzir ruído e apoiar decisões.", description: "Protótipo de gestão financeira que explora visualização de dados, organização de gastos, investimentos e metas em uma interface clara.", role: "UX/UI, arquitetura da informação e prototipagem.", href: "https://www.figma.com/proto/2y4ZguUBWlXnD2smvVHWTR/Fince?node-id=2762-1833&t=dKDqNAVuE4h8a7lr-0&scaling=scale-down&content-scaling=fixed&page-id=8%3A4", featured: false },
  { number: "04", title: "Aegon", summary: "Uma operação digital em evolução.", description: "Um espaço em construção para organizar iniciativas, dar continuidade às decisões e transformar ideias em produtos que conseguem crescer.", role: "Estrutura de produto e experimentação contínua.", href: "https://aegon-com-88qe.vercel.app/", featured: false },
];

export function HomePage() {
  return <main className="bg-[#f8f7f3] text-[#07111f]">
    <HomeHero />
    <TrajectorySection />

    <section id="projetos" className="bg-[#eaf1fb] px-6 py-24 lg:px-10 lg:py-32"><div className="mx-auto max-w-7xl"><div className="max-w-3xl"><p className="font-mono text-xs uppercase tracking-[0.22em] text-[#2166c9]">Produtos selecionados</p><h2 className="mt-5 font-[family-name:var(--font-display)] text-4xl font-medium leading-[1.02] tracking-[-0.05em] sm:text-6xl">Formas diferentes de transformar uma pergunta em produto.</h2></div><div className="mt-16 grid gap-5 lg:grid-cols-2">{projects.map((project) => <article key={project.title} className={`group flex min-h-[27rem] flex-col overflow-hidden rounded-[1.75rem] border border-[#07111f]/10 bg-[#fdfdfb] ${project.featured ? "lg:col-span-2 lg:grid lg:grid-cols-2" : ""}`}>
      {project.image && <div className={`relative overflow-hidden bg-[#07111f] ${project.featured ? "min-h-64 lg:order-2 lg:min-h-full" : "aspect-[16/9]"}`}><Image src={project.image} alt={`Tela do projeto ${project.title}`} fill sizes="(max-width: 1024px) 100vw, 50vw" className="object-cover object-top transition duration-500 group-hover:scale-105" /></div>}
      {!project.image && <div className="relative min-h-40 overflow-hidden bg-[#07111f]" style={{ backgroundImage: "linear-gradient(135deg, rgba(121,174,244,.24), transparent 55%), linear-gradient(rgba(255,255,255,.06) 1px, transparent 1px), linear-gradient(90deg, rgba(255,255,255,.06) 1px, transparent 1px)", backgroundSize: "auto, 24px 24px, 24px 24px" }}><p className="absolute bottom-5 left-6 font-mono text-xs tracking-[.18em] text-[#79aef4]">{project.title === "Aegon" ? "AEGON / EM EVOLUÇÃO" : "FINCE / PROTÓTIPO"}</p></div>}
      <div className="flex flex-1 flex-col p-7 lg:p-8"><div className="flex items-center justify-between"><span className="font-mono text-xs text-[#2166c9]">{project.number}</span><span className="rounded-full border border-[#07111f]/10 px-3 py-1 text-[11px] text-slate-500">{project.featured ? "Projeto autoral" : "Em foco"}</span></div><div className="mt-auto pt-14"><h3 className="font-[family-name:var(--font-display)] text-3xl font-semibold tracking-[-0.045em]">{project.title}</h3><p className="mt-4 text-lg leading-7 text-[#07111f]">{project.summary}</p><p className="mt-5 text-sm leading-6 text-slate-600">{project.description}</p><p className="mt-5 border-l-2 border-[#2166c9] pl-3 text-xs leading-5 text-slate-500">{project.role}</p><a href={project.href} target={project.href.startsWith("http") ? "_blank" : undefined} rel={project.href.startsWith("http") ? "noreferrer" : undefined} className="mt-7 inline-flex items-center gap-2 text-sm font-semibold text-[#2166c9] transition group-hover:gap-3">{project.title === "Criative Lab" ? "Acompanhar o projeto" : project.title === "Aegon" ? "Conhecer a operação" : "Ver protótipo"} <ArrowUpRight size={16} /></a></div></div></article>)}</div></div></section>

    <section id="universos" className="overflow-hidden bg-[#07111f] px-6 py-24 text-white lg:px-10 lg:py-32"><div className="relative mx-auto grid max-w-7xl gap-12 lg:grid-cols-[1.08fr_.92fr] lg:items-end"><div className="absolute -right-32 -top-40 h-[30rem] w-[30rem] rounded-full bg-[#2166c9]/25 blur-3xl" /><div className="relative"><p className="font-mono text-xs uppercase tracking-[0.22em] text-[#79aef4]">Universos de criação</p><h2 className="mt-5 max-w-4xl font-[family-name:var(--font-display)] text-4xl font-medium leading-[1.02] tracking-[-0.055em] sm:text-6xl">A mesma intenção muda de forma conforme o problema muda.</h2><p className="mt-7 max-w-2xl text-lg leading-8 text-white/68">Cada universo vai mostrar uma forma de trabalhar. O primeiro está aberto: UX/UI, onde uma pergunta começa a encontrar uma interface.</p></div><Link href="/p/ux-ui" className="relative group overflow-hidden rounded-[1.75rem] border border-white/15 bg-white/[0.05] p-7 transition hover:-translate-y-1 hover:border-[#F24E1E]/80"><div className="flex items-center justify-between"><span className="font-mono text-xs tracking-[0.18em] text-[#F24E1E]">UNIVERSO 01</span><ArrowUpRight className="transition group-hover:translate-x-1 group-hover:-translate-y-1" size={19} /></div><Layers3 className="mt-16 text-[#F24E1E]" size={30} /><h3 className="mt-5 font-[family-name:var(--font-display)] text-4xl font-semibold tracking-[-0.05em]">UX/UI</h3><p className="mt-3 max-w-sm text-sm leading-6 text-white/62">Do problema ao rascunho: contexto, jornada, decisão e um canvas para explorar caminhos.</p><span className="mt-8 inline-flex items-center gap-2 text-sm font-semibold text-[#F24E1E]">Entrar no espaço <ArrowUpRight size={16} /></span></Link></div></section>

    <section id="contato" className="bg-[#07111f] px-6 py-24 text-white lg:px-10 lg:py-32"><div className="mx-auto grid max-w-7xl gap-12 border-t border-white/10 pt-24 lg:grid-cols-[1.2fr_.8fr] lg:items-end"><div><p className="font-mono text-xs uppercase tracking-[0.22em] text-[#79aef4]">Vamos começar por uma conversa</p><h2 className="mt-5 max-w-3xl font-[family-name:var(--font-display)] text-4xl font-medium leading-[1.02] tracking-[-0.055em] sm:text-6xl">Tem um problema que merece uma boa solução?</h2></div><div className="space-y-4"><a href="mailto:emanuelsantossouzajesus@gmail.com" className="flex items-center justify-between border-b border-white/20 pb-4 text-lg transition hover:border-[#79aef4] hover:text-[#79aef4]">emanuelsantossouzajesus@gmail.com <Mail size={19} /></a><div className="flex gap-5 pt-3 text-sm text-white/65"><a className="inline-flex items-center gap-2 transition hover:text-white" href="https://github.com/emanuelsantoz" target="_blank" rel="noreferrer"><Github size={17} /> GitHub</a><a className="inline-flex items-center gap-2 transition hover:text-white" href="https://www.linkedin.com/in/emanu-ell/" target="_blank" rel="noreferrer"><Linkedin size={17} /> LinkedIn</a></div></div></div><div className="mx-auto mt-20 flex max-w-7xl items-center justify-between border-t border-white/10 pt-6 text-xs text-white/45"><span>Emanuel Santos</span><span>ES/0 · 2026</span></div></section>
  </main>;
}
