import Link from "next/link";
import { ArrowUpRight, Github, Layers3, Linkedin, Mail } from "lucide-react";
import { EmanuelLogo } from "@/components/brand/EmanuelLogo";
import { HomeHero } from "@/components/pages/HomeHero";
import { NexusSection } from "@/components/pages/NexusSection";
import { PortfolioPointerLight } from "@/components/pages/PortfolioPointerLight";
import { TrajectorySection } from "@/components/pages/TrajectorySection";
import { WorkShowcase, type ShowcaseItem } from "@/components/pages/WorkShowcase";

const showcaseItems: ShowcaseItem[] = [
  { id: "creative-lab", code: "ES/02", category: "Produto educacional", status: "Em evolução", title: "Criative Lab", headline: "Projetos acadêmicos não deveriam terminar na apresentação.", question: "Como fazer com que projetos de estudantes continuem visíveis, contextualizados e capazes de gerar novas conversas depois da entrega?", decision: "Construir um espaço digital que recebe, organiza e apresenta projetos com contexto para quem cria, acompanha e descobre o que foi feito.", result: "Uma base de produto em evolução para transformar produção acadêmica em continuidade, comunidade e repertório compartilhado.", role: "Estratégia de produto, identidade, experiência e desenvolvimento da plataforma.", signals: ["Projetos acadêmicos", "Comunidade", "Visibilidade", "Em evolução"], connections: ["Educação", "Comunidade", "Identidade", "Tecnologia"], flow: ["Receber projetos", "Organizar o contexto", "Dar visibilidade", "Criar continuidade"], disciplines: ["Estratégia de produto", "UX/UI", "Identidade visual", "Desenvolvimento"], visualTone: "orange" },
  { id: "itesam", code: "PRD/01", category: "Plataforma institucional e atendimento", status: "Ativo em produção", title: "ITESAM", headline: "Uma presença institucional que também organiza cadastro, consulta de dados e abertura de chamados.", question: "Como atender uma necessidade institucional recorrente com uma solução confiável, simples de operar e adequada ao volume real de uso?", decision: "Manter uma arquitetura monolítica em PHP com MySQL e modelagem compacta, sem complexidade desnecessária: o produto precisava resolver bem uma dor pequena, não simular uma escala que não existe.", result: "Uma plataforma publicada, usada e mantida até hoje, com atendimento por chamados e uma esteira de entrega que leva alterações revisadas à produção.", role: "Projeto desenvolvido em parceria. Meu sócio definiu o layout dentro do padrão do cliente; eu assumi backend, endpoints, modelagem, regras de negócio, integração com frontend, deploy, versionamento, suporte e evolução da entrega contínua.", signals: ["Ativo em produção", "PHP monolítico", "MySQL compacto", "CI/CD"], connections: ["Institucional", "Atendimento", "Dados", "Operação"], flow: ["Layout alinhado ao cliente", "Modelagem compacta", "Cadastro, consulta e chamados", "Integração com frontend", "Deploy", "Entrega contínua"], disciplines: ["Backend e regras de negócio", "Integração de sistemas", "Testes unitários, de integração e E2E", "Versionamento e CI/CD"], link: { href: "https://itesam.org.br/", label: "Visitar plataforma" }, visualTone: "blue" },
  { id: "presenca-evento", code: "CASE/01", category: "Sistema operacional validado", status: "Usado em evento", title: "Cadastro e presença para evento infantil", headline: "Uma operação de três dias sem papel, sorteio manual ou equipes definidas por feeling.", question: "Como manter cadastro, presença, sorteio e formação de equipes funcionando durante um evento, sem transformar a equipe em digitadora de planilhas?", decision: "Criar uma infraestrutura proporcional ao evento: Lovable e Google Sheets, com regras de presença, elegibilidade, faixa etária e ordem de chegada no próprio fluxo.", result: "43 crianças foram acompanhadas durante três dias, somando cerca de 15 horas de operação. A equipe pôde focar no acolhimento e na execução, não no papel.", role: "Concepção do fluxo, regras de negócio, experiência, suporte à operação e infraestrutura.", signals: ["43 crianças", "3 dias", "15 horas", "6 pessoas na operação"], connections: ["Pessoas", "Operação", "Regras", "Dados"], flow: ["Cadastro", "Presença por dia", "Validação", "Elegibilidade", "Sorteio", "Equipes por faixa etária"], disciplines: ["Desenho de operação", "Regras de negócio", "Experiência de uso", "Infraestrutura proporcional"], video: "/videos/works/cadastro-presenca.mp4", link: { href: "https://ipb-forms-flow.lovable.app", label: "Abrir solução" }, visualTone: "green" },
  { id: "rotas-inteligentes", code: "CASE/02", category: "Protótipo autoral", status: "Em exploração", title: "Rotas Inteligentes", headline: "Mobilidade urbana com mais contexto antes de uma escolha de rota.", question: "Como transformar dúvidas de deslocamento em uma experiência que ajuda a comparar caminhos, tempo e possibilidades com menos ruído?", decision: "Prototipar uma jornada que parte da necessidade de se deslocar e organiza informação para apoiar a decisão antes do movimento.", result: "Um protótipo para testar clareza, confiança e comparações de rota com pessoas que vivem escolhas diferentes no dia a dia.", role: "Conceito, pesquisa, experiência e prototipagem por Emanuel Santos.", signals: ["Mobilidade", "Decisão", "Protótipo", "Teste"], connections: ["Mobilidade", "Comunicação", "Segurança", "Experiência"], flow: ["Entender o trajeto", "Comparar opções", "Decidir com contexto", "Acompanhar o caminho"], disciplines: ["Pesquisa", "Arquitetura da informação", "UX/UI", "Prototipagem"], link: { href: "https://www.figma.com/proto/p2nGg4cLvSvimsAAhEkviB/Rotas-Inteligentes?node-id=214-1010&starting-point-node-id=214%3A1010", label: "Abrir protótipo" }, visualTone: "blue" },
  { id: "fince", code: "CASE/03", category: "Protótipo autoral", status: "Em exploração", title: "Fince", headline: "Uma experiência financeira pessoal que reduz ruído antes de pedir uma decisão.", question: "Como apresentar gastos, metas e investimentos de um jeito que ajude pessoas a entender a própria vida financeira?", decision: "Explorar hierarquia visual, linguagem e organização de dados para que a interface comece pela compreensão, não pela complexidade.", result: "Um protótipo para validar leitura de informações, priorização e próximos passos em cenários financeiros cotidianos.", role: "UX/UI, arquitetura da informação e prototipagem.", signals: ["Finanças", "Dados", "Clareza", "Protótipo"], connections: ["Finanças", "Dados", "Decisão", "Interface"], flow: ["Organizar dados", "Entender o cenário", "Definir prioridades", "Acompanhar metas"], disciplines: ["Arquitetura da informação", "Visualização de dados", "UX/UI", "Prototipagem"], link: { href: "https://www.figma.com/proto/2y4ZguUBWlXnD2smvVHWTR/Fince?node-id=2762-1833&t=dKDqNAVuE4h8a7lr-0&scaling=scale-down&content-scaling=fixed&page-id=8%3A4", label: "Abrir protótipo" }, visualTone: "violet" },
];

const method = [
  { number: "01", title: "Entender", text: "Escutar pessoas, observar o contexto e encontrar a tensão que realmente precisa avançar." },
  { number: "02", title: "Estruturar", text: "Transformar descobertas em proposta, fluxos, arquitetura e critérios claros de decisão." },
  { number: "03", title: "Construir", text: "Conectar design, engenharia, conteúdo e testes em algo que as pessoas consigam usar." },
  { number: "04", title: "Continuar", text: "Publicar, acompanhar e evoluir sem deixar uma boa ideia terminar na primeira entrega." },
];

export function HomePage() {
  return <main className="portfolio-shell bg-[#f8f7f3] text-[#07111f]"><PortfolioPointerLight /><HomeHero />
    <section id="construcoes" className="bg-[#eaf1fb] px-6 py-24 lg:px-10 lg:py-32"><div className="mx-auto max-w-7xl"><SectionHeading eyebrow="Construções em movimento" title="Menos promessa. Mais contexto sobre o que já começou a resolver algo." text="A vitrine mostra produtos, sistemas e protótipos por uma pergunta simples: qual problema estava em jogo, qual decisão foi tomada e o que isso colocou em movimento." /><div className="mt-16"><WorkShowcase items={showcaseItems} /></div><aside className="mt-8 flex flex-col gap-5 rounded-[1.5rem] border border-[#07111f]/10 bg-white/70 p-6 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-mono text-[10px] uppercase tracking-[0.18em] text-[#2166c9]">Iniciativa em definição</p><h3 className="mt-2 font-[family-name:var(--font-display)] text-2xl font-semibold tracking-[-0.04em]">Aegon</h3><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-600">Uma iniciativa que ainda está encontrando nome, proposta e relação com a marca antes de ganhar uma presença pública maior.</p></div><a href="#contato" className="inline-flex shrink-0 items-center gap-2 text-sm font-semibold text-[#2166c9] transition hover:gap-3">Conversar sobre a iniciativa <ArrowUpRight size={16} /></a></aside></div></section>
    <NexusSection />
    <section id="metodo" className="overflow-hidden bg-[#07111f] px-6 py-24 text-white lg:px-10 lg:py-32"><div className="mx-auto max-w-7xl"><SectionHeading dark eyebrow="Método de construção" title="Clareza não é uma etapa. É o que orienta cada etapa." text="Estratégia, experiência e engenharia funcionam como partes de uma mesma construção, guiadas pelo que as pessoas precisam conseguir fazer no fim." /><ol className="mt-16 grid gap-px overflow-hidden rounded-[1.75rem] border border-white/10 bg-white/10 md:grid-cols-2 lg:grid-cols-4">{method.map((step) => <li key={step.number} className="group min-h-64 bg-[#07111f] p-7 transition hover:bg-[#0d1f37] lg:p-8"><span className="font-mono text-xs tracking-[0.2em] text-[#2f7de1]">{step.number}</span><h3 className="mt-14 font-[family-name:var(--font-display)] text-3xl font-semibold tracking-[-0.045em]">{step.title}</h3><p className="mt-4 text-sm leading-6 text-white/63">{step.text}</p></li>)}</ol></div></section>
    <TrajectorySection />
    <section id="universos" className="overflow-hidden bg-[#10243f] px-6 py-24 text-white lg:px-10 lg:py-32"><div className="relative mx-auto grid max-w-7xl gap-12 lg:grid-cols-[1.08fr_.92fr] lg:items-end"><div className="absolute -right-32 -top-40 h-[30rem] w-[30rem] rounded-full bg-[#2166c9]/25 blur-3xl" /><div className="relative"><p className="font-mono text-xs uppercase tracking-[0.22em] text-[#2f7de1]">Universos de criação</p><h2 className="mt-5 max-w-4xl font-[family-name:var(--font-display)] text-4xl font-medium leading-[1.02] tracking-[-0.055em] sm:text-6xl">A mesma intenção muda de forma conforme o problema muda.</h2><p className="mt-7 max-w-2xl text-lg leading-8 text-white/68">Os universos mostram habilidades que entram em cada construção. O primeiro está aberto: UX/UI, onde uma pergunta começa a encontrar uma interface.</p></div><Link href="/p/ux-ui" className="relative group overflow-hidden rounded-[1.75rem] border border-white/15 bg-white/[0.05] p-7 transition hover:-translate-y-1 hover:border-[#f24e1e]/80 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#2f7de1]"><div className="flex items-center justify-between"><span className="font-mono text-xs tracking-[0.18em] text-[#f24e1e]">UNIVERSO 01</span><ArrowUpRight className="transition group-hover:translate-x-1 group-hover:-translate-y-1" size={19} /></div><Layers3 className="mt-16 text-[#f24e1e]" size={30} /><h3 className="mt-5 font-[family-name:var(--font-display)] text-4xl font-semibold tracking-[-0.05em]">UX/UI</h3><p className="mt-3 max-w-sm text-sm leading-6 text-white/62">Do problema ao rascunho: contexto, jornada, decisão e um canvas para explorar caminhos.</p><span className="mt-8 inline-flex items-center gap-2 text-sm font-semibold text-[#f24e1e]">Entrar no espaço <ArrowUpRight size={16} /></span></Link></div></section>
    <section id="contato" className="bg-[#07111f] px-6 py-24 text-white lg:px-10 lg:py-32"><div className="mx-auto grid max-w-7xl gap-12 border-t border-white/10 pt-24 lg:grid-cols-[1.2fr_.8fr] lg:items-end"><div><p className="font-mono text-xs uppercase tracking-[0.22em] text-[#2f7de1]">Vamos começar por uma conversa</p><h2 className="mt-5 max-w-3xl font-[family-name:var(--font-display)] text-4xl font-medium leading-[1.02] tracking-[-0.055em] sm:text-6xl">Tem um processo confuso, uma ideia sem forma ou um produto que precisa evoluir?</h2></div><div className="space-y-5"><a href="mailto:emanuelsantossouzajesus@gmail.com?subject=Quero%20conversar%20sobre%20um%20projeto" className="inline-flex items-center gap-2 rounded-full bg-white px-5 py-3 text-sm font-semibold text-[#07111f] transition hover:bg-[#dbeafe] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#2f7de1] focus-visible:ring-offset-4 focus-visible:ring-offset-[#07111f]">Vamos mapear o próximo passo <ArrowUpRight size={16} /></a><a href="mailto:emanuelsantossouzajesus@gmail.com" className="flex items-center justify-between border-b border-white/20 pb-4 text-base transition hover:border-[#2f7de1] hover:text-[#2f7de1] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#2f7de1]">emanuelsantossouzajesus@gmail.com <Mail size={19} /></a><div className="flex gap-5 pt-1 text-sm text-white/65"><a className="inline-flex items-center gap-2 transition hover:text-white" href="https://github.com/emanuelsantoz" target="_blank" rel="noreferrer"><Github size={17} /> GitHub</a><a className="inline-flex items-center gap-2 transition hover:text-white" href="https://www.linkedin.com/in/emanu-ell/" target="_blank" rel="noreferrer"><Linkedin size={17} /> LinkedIn</a></div></div></div><div className="mx-auto mt-20 flex max-w-7xl items-center justify-between border-t border-white/10 pt-6 text-xs text-white/45"><EmanuelLogo tone="light" variant="compact" className="opacity-80" /><div className="flex items-center gap-5"><Link href="/brand" className="transition hover:text-white">Biblioteca de marca</Link><span>ES/0 · 2026</span></div></div></section>
  </main>;
}

function SectionHeading({ eyebrow, title, text, dark = false }: { eyebrow: string; title: string; text: string; dark?: boolean }) {
  return <div className="grid gap-8 lg:grid-cols-[1.2fr_.8fr] lg:items-end"><div><p className={`font-mono text-xs uppercase tracking-[0.22em] ${dark ? "text-[#2f7de1]" : "text-[#2166c9]"}`}>{eyebrow}</p><h2 className="mt-5 max-w-4xl font-[family-name:var(--font-display)] text-4xl font-medium leading-[1.02] tracking-[-0.05em] sm:text-6xl">{title}</h2></div><p className={`max-w-xl text-base leading-7 lg:text-lg ${dark ? "text-white/65" : "text-slate-600"}`}>{text}</p></div>;
}
