import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { ArrowUpRight } from "lucide-react";
import { PortfolioLayout } from "@/components/portfolio/PortfolioLayout";

export const metadata: Metadata = { title: "Sobre Emanuel", description: "Trajetória de Emanuel Santos em desenvolvimento, produto e construção de soluções digitais.", alternates: { canonical: "/sobre" } };
const timeline = [["2023–2024", "Formação Barracred Conecta", "Vivência prática em tecnologia, segurança e desenvolvimento."], ["2024–2025", "Jovem Aprendiz em TI", "Suporte, documentação, gestão de acessos e uma base profissional."], ["2025–hoje", "Analista de Desenvolvimento Jr.", "Atuação em sistemas internos, melhoria contínua e soluções para pessoas reais."]];
export default function AboutPage() { return <PortfolioLayout><section className="px-6 py-16 lg:px-10 lg:py-24"><div className="mx-auto grid max-w-6xl gap-12 lg:grid-cols-[.75fr_1.25fr] lg:items-start"><div className="relative overflow-hidden rounded-[2rem] bg-[#07111f]"><Image src="/images/emanuel-at-work.jpeg" alt="Emanuel Santos trabalhando" width={1200} height={1600} className="aspect-[4/5] w-full object-cover" /></div><div><p className="font-mono text-xs uppercase tracking-[0.22em] text-[#2166c9]">Sobre Emanuel</p><h1 className="mt-5 font-[family-name:var(--font-display)] text-5xl font-medium leading-[1.02] tracking-[-0.055em] sm:text-6xl">Desenvolvimento é a ferramenta. Resolver é o trabalho.</h1><div className="mt-8 max-w-2xl space-y-5 text-lg leading-8 text-slate-600"><p>A jornada em tecnologia começou pela curiosidade de entender como as coisas funcionam. Com o tempo, essa curiosidade virou uma forma de observar problemas, organizar caminhos e dar forma a soluções digitais.</p><p>Entre desafios profissionais e produtos autorais, Emanuel conecta contexto, experiência e construção. A meta não é apenas entregar uma interface ou sistema, mas criar algo que tenha motivo para existir e espaço para continuar.</p></div><ol className="mt-12 space-y-7 border-l border-[#2166c9]/30 pl-6">{timeline.map(([period, title, text]) => <li key={title}><p className="font-mono text-xs text-[#2166c9]">{period}</p><h2 className="mt-1 font-[family-name:var(--font-display)] text-2xl font-semibold tracking-[-0.03em]">{title}</h2><p className="mt-2 text-sm leading-6 text-slate-600">{text}</p></li>)}</ol><Link href="/contato" className="mt-12 inline-flex items-center gap-2 rounded-full bg-[#07111f] px-5 py-3 text-sm font-semibold text-white hover:bg-[#2166c9]">Iniciar uma conversa <ArrowUpRight size={16} /></Link></div></div></section></PortfolioLayout>; }
